### PR TITLE
fix invalid js

### PR DESCRIPTION
**Pull request by timc13**
Cannot assign a property to a string.

### CODE REVIEW

**Comment by jmdobry** [comment]
Thanks! Though I came up with a non-breaking fix.

**Comment by timc13** [comment]
I see you just wrapped that in a try/except, but I'm curious - when that would ever not throw an exception?  why is that line even necessary?

**Comment by jmdobry** [comment]
There have been many angular modules published in UMD format and for a time the "best practice" was to export a module that had a `name` property that corresponds to the name of the angular module that your app's module depends on. I personally prefer exporting the name directly, but, some people still try to do `.name`...

Try this in devtools: `'js-data'.name = 'js-data'`, i've never seen that throw an error in my use of js-data-angular.

**Comment by timc13** [comment]
interesting...thanks for the explanation!

**Pull request closed without merging**
